### ISSUE TITLE
question about using demux

### ISSUE THREAD

**Issue by jy427** [YeoLab/eclipdemux#1]
Hi,

I have some questions when I use the eclipdemux, Please  take a look at the questions I mentioned below.

I  can call the main function (demux -h), but when I run the command, I get an error.

**The command I used:**
> demux --metrics IP3_PE_clip.---.--.metrics --expectedbarcodeida bc1 --expectedbarcodeidb bc2 --fastq_1 ../../0-data/R21046039-SGC-IP-SGC-IP_combined_R1.fastq.gz --fastq_2 ../../0-data/R21046039-SGC-IP-SGC-IP_combined_R2.fastq.gz --newname IP3_clip --dataset IP3_PE --barcodesfile ./barcode.fasta --length 10 > IP3.log

**error:**
> Traceback (most recent call last):
  File "/home/disk/software/anaconda3/bin/demux", line 33, in <module>
    sys.exit(load_entry_point('eclipdemux-distribution==0.0.1', 'console_scripts', 'demux')())
  File "/home/disk/software/anaconda3/lib/python3.8/site-packages/eclipdemux_distribution-0.0.1-py3.8.egg/eclipdemux_package/demux.py", line 907, in main
    demux(datastr,
  File "/home/disk/software/anaconda3/lib/python3.8/site-packages/eclipdemux_distribution-0.0.1-py3.8.egg/eclipdemux_package/demux.py", line 822, in demux
    bcassigned = assignbarcode(fastqread1["sequence"],
  File "/home/disk/software/anaconda3/lib/python3.8/site-packages/eclipdemux_distribution-0.0.1-py3.8.egg/eclipdemux_package/demux.py", line 430, in assignbarcode
    distances_to_bcseqs = [(hamming_loose(bcfound, bcseq), bcseq)
  File "/home/disk/software/anaconda3/lib/python3.8/site-packages/eclipdemux_distribution-0.0.1-py3.8.egg/eclipdemux_package/demux.py", line 430, in <listcomp>
    distances_to_bcseqs = [(hamming_loose(bcfound, bcseq), bcseq)
  File "/home/disk/software/anaconda3/lib/python3.8/site-packages/eclipdemux_distribution-0.0.1-py3.8.egg/eclipdemux_package/demux.py", line 360, in hamming_loose
    return _hamming(_matching_loose, word1, word2)
  File "/home/disk/software/anaconda3/lib/python3.8/site-packages/eclipdemux_distribution-0.0.1-py3.8.egg/eclipdemux_package/demux.py", line 332, in _hamming
    return sum(not matching_function(letter1, letter2)
  File "/home/disk/software/anaconda3/lib/python3.8/site-packages/eclipdemux_distribution-0.0.1-py3.8.egg/eclipdemux_package/demux.py", line 332, in <genexpr>
    return sum(not matching_function(letter1, letter2)
  File "/home/disk/software/anaconda3/lib/python3.8/site-packages/eclipdemux_distribution-0.0.1-py3.8.egg/eclipdemux_package/demux.py", line 312, in _matching_loose
    _assert_in_alphabet(nucl1)
  File "/home/disk/software/anaconda3/lib/python3.8/site-packages/eclipdemux_distribution-0.0.1-py3.8.egg/eclipdemux_package/demux.py", line 288, in _assert_in_alphabet
    raise_with_traceback(IllegalBarcodeSeqValueError(nucl))
  File "/home/disk/software/anaconda3/lib/python3.8/site-packages/future/utils/__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
eclipdemux_package.demux.IllegalBarcodeSeqValueError: 65

I also called the python script(**demux.py**) directly and it ran successfully

**The command I used:**
> demux.py --metrics IP2_PE_clip.---.--.metrics --expectedbarcodeida bc1 --expectedbarcodeidb bc2 --fastq_1 ../../0-data/R21046039-SGC-IP-SGC-IP_combined_R1.fastq.gz --fastq_2 ../../0-data/R21046039-SGC-IP-SGC-IP_combined_R2.fastq.gz --newname IP2_clip --dataset IP2_PE --barcodesfile ./barcode.fasta --length 10 > IP2.log

However, the file of NIL is very large, while the file of barcode(bc1 and bc2) is very small. Which file should I use for subsequent analysis?
![image](https://user-images.githubusercontent.com/48338075/122365172-079cff80-cf8d-11eb-868d-2ecaf717d30f.png)

**Here are my questions:**
1、Is there any difference between calling demux and calling the demux.py directly? 
2、How do I handle the above error when I run demux?
3、When I provide specific barcode for IP, but the result shows that the NIL file is larger than the corresponding barcode file , which file should I use for subsequent analysis?

**Comment by nikou123456** [comment]
> Hi,
> 
> I have some questions when I use the eclipdemux, Please take a look at the questions I mentioned below.
> 
> I can call the main function (demux -h), but when I run the command, I get an error.
> 
> **The command I used:**
> 
> > demux --metrics IP3_PE_clip.---.--.metrics --expectedbarcodeida bc1 --expectedbarcodeidb bc2 --fastq_1 ../../0-data/R21046039-SGC-IP-SGC-IP_combined_R1.fastq.gz --fastq_2 ../../0-data/R21046039-SGC-IP-SGC-IP_combined_R2.fastq.gz --newname IP3_clip --dataset IP3_PE --barcodesfile ./barcode.fasta --length 10 > IP3.log
> 
> **error:**
> 
> > Traceback (most recent call last):
> > File "/home/disk/software/anaconda3/bin/demux", line 33, in 
> > sys.exit(load_entry_point('eclipdemux-distribution==0.0.1', 'console_scripts', 'demux')())
> > File "/home/disk/software/anaconda3/lib/python3.8/site-packages/eclipdemux_distribution-0.0.1-py3.8.egg/eclipdemux_package/demux.py", line 907, in main
> > demux(datastr,
> > File "/home/disk/software/anaconda3/lib/python3.8/site-packages/eclipdemux_distribution-0.0.1-py3.8.egg/eclipdemux_package/demux.py", line 822, in demux
> > bcassigned = assignbarcode(fastqread1["sequence"],
> > File "/home/disk/software/anaconda3/lib/python3.8/site-packages/eclipdemux_distribution-0.0.1-py3.8.egg/eclipdemux_package/demux.py", line 430, in assignbarcode
> > distances_to_bcseqs = [(hamming_loose(bcfound, bcseq), bcseq)
> > File "/home/disk/software/anaconda3/lib/python3.8/site-packages/eclipdemux_distribution-0.0.1-py3.8.egg/eclipdemux_package/demux.py", line 430, in 
> > distances_to_bcseqs = [(hamming_loose(bcfound, bcseq), bcseq)
> > File "/home/disk/software/anaconda3/lib/python3.8/site-packages/eclipdemux_distribution-0.0.1-py3.8.egg/eclipdemux_package/demux.py", line 360, in hamming_loose
> > return _hamming(_matching_loose, word1, word2)
> > File "/home/disk/software/anaconda3/lib/python3.8/site-packages/eclipdemux_distribution-0.0.1-py3.8.egg/eclipdemux_package/demux.py", line 332, in _hamming
> > return sum(not matching_function(letter1, letter2)
> > File "/home/disk/software/anaconda3/lib/python3.8/site-packages/eclipdemux_distribution-0.0.1-py3.8.egg/eclipdemux_package/demux.py", line 332, in 
> > return sum(not matching_function(letter1, letter2)
> > File "/home/disk/software/anaconda3/lib/python3.8/site-packages/eclipdemux_distribution-0.0.1-py3.8.egg/eclipdemux_package/demux.py", line 312, in _matching_loose
> > _assert_in_alphabet(nucl1)
> > File "/home/disk/software/anaconda3/lib/python3.8/site-packages/eclipdemux_distribution-0.0.1-py3.8.egg/eclipdemux_package/demux.py", line 288, in _assert_in_alphabet
> > raise_with_traceback(IllegalBarcodeSeqValueError(nucl))
> > File "/home/disk/software/anaconda3/lib/python3.8/site-packages/future/utils/**init**.py", line 446, in raise_with_traceback
> > raise exc.with_traceback(traceback)
> > eclipdemux_package.demux.IllegalBarcodeSeqValueError: 65
> 
> I also called the python script(**demux.py**) directly and it ran successfully
> 
> **The command I used:**
> 
> > demux.py --metrics IP2_PE_clip.---.--.metrics --expectedbarcodeida bc1 --expectedbarcodeidb bc2 --fastq_1 ../../0-data/R21046039-SGC-IP-SGC-IP_combined_R1.fastq.gz --fastq_2 ../../0-data/R21046039-SGC-IP-SGC-IP_combined_R2.fastq.gz --newname IP2_clip --dataset IP2_PE --barcodesfile ./barcode.fasta --length 10 > IP2.log
> 
> However, the file of NIL is very large, while the file of barcode(bc1 and bc2) is very small. Which file should I use for subsequent analysis?
> ![image](https://user-images.githubusercontent.com/48338075/122365172-079cff80-cf8d-11eb-868d-2ecaf717d30f.png)
> 
> **Here are my questions:**
> 1、Is there any difference between calling demux and calling the demux.py directly?
> 2、How do I handle the above error when I run demux?
> 3、When I provide specific barcode for IP, but the result shows that the NIL file is larger than the corresponding barcode file , which file should I use for subsequent analysis?

Hi there,
Could you share with me how to install eclipdemux and use it ?
I installed eclipdemux with following command.
```
sudo python setup.py build
sudo python setup.py install
export PAHT=$PATH:...
```
But it doesn't work when I use 'eclipdemux' order.
